Fix RuntimeError after closing loop that used run_in_executor
