Fix :exc:`NameError` in command-line interface of :mod:`py_compile`.
